FROM ruby:2.6

LABEL maintainer="bas@fourstack.nl"

RUN apt-get update -yqq && apt-get install -yqq --no-install-recommends \
  netcat \
  nodejs

COPY Gemfile* /usr/src/app/
WORKDIR /usr/src/app

ENV BUNDLE_PATH /gems

RUN bundle install

COPY . /usr/src/app/

RUN ["chmod", "+x", "/usr/src/app/wait-for"]
RUN bin/rails assets:precompile

CMD ["bin/rails", "s", "-b", "0.0.0.0"]
